version: '3'

services:
    reverse_proxy:
        image: nginx:1.17
        volumes:
          - "$PWD/dev-nginx.conf:/etc/nginx/nginx.conf"
          - ./webapp/public:/home/isucon/isucon9q-kakiiredokinow/webapp/public
        ports:
          - "80:80"
        depends_on:
          - db
          - app

    app:
        build:
            context: ./
            dockerfile: Dockerfile_go
        command: "make -C /go/src/isucon/webapp/go build run"
        volumes:
          - "$PWD:/go/src/isucon"
        environment:
            GOPATH: "/go"
            MYSQL_HOST: db
        ports:
          - "8000:8000"
        depends_on:
          - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: "isucari"
            MYSQL_USER: "isucari"
            MYSQL_PASSWORD: "isucari"
        volumes:
          - "$PWD/mysql-dump.sql.gz:/docker-entrypoint-initdb.d/mysql-dump.sql.gz"
