version: '3'

services:
    reverse_proxy:
        build:
            context: .
            dockerfile: Dockerfile_varnish
        ports:
          - "80:80"
    backend:
        build:
            context: .
            dockerfile: Dockerfile_go
        command: "./server"
