version: '3'

services:
    reverse_proxy:
        build:
            context: varnish
        ports:
          - "80:80"
    backend:
        build:
            context: app
        command: "./server"
    db:
        image: mysql:8
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: "app-db"

